# Generated by Django 3.0.3 on 2020-07-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusinfo',
            name='email',
            field=models.EmailField(error_messages={'required': 'Please enter valid email'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='name',
            field=models.CharField(error_messages={'required': 'Please enter your name'}, max_length=50),
        ),
    ]
