# Generated by Django 3.0.3 on 2020-07-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0002_auto_20200709_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusinfo',
            name='email',
            field=models.EmailField(error_messages={'required': 'Please enter valid email'}, max_length=254),
        ),
    ]
